-- General stuff
require('plugins')
require('keymappings')
require('settings')
require('colorscheme')
require('ls-autocommands')

-- Plugins
require('ls-nvimtree')
require('ls-gitsigns')
require('ls-galaxyline')
require('ls-colorizer')
require('ls-barbar')
require('ls-treesitter')
require('ls-autopairs')
require('ls-rnvimr')
require('ls-comment')
require('ls-fterm')
require('ls-telescope')
require('ls-quickscope')
require('ls-rooter')
require('ls-numb')
require('ls-startscreen')
require('ls-compe')

-- LSP
require('lsp')
require('lsp.lua-ls')
require('lsp.python-ls')
require('lsp.yaml-ls')
require('lsp.vim-ls')
require('lsp.typescript-ls')
